networks:
  web:
    name: web
    external: true

services:
  global-proxy:
    image: caddy:2
    container_name: global-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites:/etc/caddy/sites
      - /home/ubuntu/personal-website/dist:/usr/share/caddy
      - backend_code:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:
  # Define this to sync with your inventory-backend
  backend_code:
    external: true
